cleanup velocity smoother
4am-robotics/cob_control pull request #133
Opened 2017-02-13 17:28 UTC by ipa-fxm

@ipa-bnm 

While trying to understand the velocity smoother (limiter :wink:), I did some cleanup, i.e.
 - threading
 - parameter/dynamic-reconfigure handling

Also, I made `robot_feedback` dynamically reconfigurable and some consistency improvements (e.g. condition for `input_active`). Further, the acceleration/deceleration limit is now actually considering proper SI units as well as `safe_factor` for both acceleration and deceleration.

Behaviour is still the same:
![fixed_smoother](https://cloud.githubusercontent.com/assets/508006/22894612/f3b34e16-f219-11e6-85bb-11de40441d29.png)
![current_smoother](https://cloud.githubusercontent.com/assets/508006/22894629/fc561c74-f219-11e6-8f9a-41606dfb0ca7.png)

might need to tune the parameters, though due to now actually considering proper units...will test it on robot HW asap.

Requires  due to parameter renaming

2017-02-13 17:54 UTC, ipa-fxm commented
Here is an example behavior for a random step input:
![fix_smoother_step](https://cloud.githubusercontent.com/assets/508006/22895746/e5f7cda2-f21d-11e6-8d66-aa791d852394.png)

2017-02-14 13:30 UTC, floweisshardt approved these changes

2017-02-14 14:21 UTC, ipa-fxm commented
Do not merge without feedback from @ipa-bnm!

2017-02-15 16:28 UTC, benmaidel requested changes

2017-02-15 16:28 UTC, benmaidel commented on cob_base_velocity_smoother/include/cob_base_velocity_smoother/velocity_smoother.h
> -    nth_element(values.begin(), values.begin() + values.size()/2, values.end());
Why do you remove this? This is necessary to calculate the median!

2017-02-15 16:28 UTC, benmaidel commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +    cb_avg_time = 1.0/frequency;
This assumption is wrong. We should not expect to receive messages with the frequency of our own node. Please revert or introduce separate param

2017-02-15 16:28 UTC, benmaidel commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +      (last_command > std::min(PERIOD_RECORD_SIZE*cb_avg_time, 0.5))) //missed PERIOD_RECORD_SIZE input cycles or no input for 0.5 secs
`PERIOD_RECORD_SIZE` has no direct connection to `cb_avg_time`. `PERIOD_RECORD_SIZE` is just the size of the container which is used to calculate the frequency in which the twist callback is called! So if we decide to increase the `period_record` container size, the `cb_avg_time` will just get more precise but not longer. If we would like to get rid of the magic number `3.0` we should introduce a new param. E.g. `max_missed_input_cycles`

2017-02-15 16:28 UTC, benmaidel commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +      ROS_WARN_STREAM("...leaving us a non-zero target velocity ("
If you start more than one node inside a launch file you do not know where this ROS_WARN is coming from. There could be other ros messages in between...

2017-02-15 16:28 UTC, benmaidel commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +  double accel_w  = (input_active)?accel_lim_w :safe_factor*accel_lim_w;
Why do you multiply the acceleration limits with the `safe_ factor`? We do not like to do this! Acceleration is always the fixed limits from parameters. Only during deceleration the `decel_factor` or `safe_factor` should be used!

2017-02-15 16:28 UTC, benmaidel commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +      ((last_command > std::min(PERIOD_RECORD_SIZE*cb_avg_time, 0.5))    || //missed PERIOD_RECORD_SIZE input cycles or no input for 0.5 secs
See comment above. (PERIOD_RECORD_SIZE)

2017-02-15 16:28 UTC, ipa-bnm commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +    //actual_aw = (std::abs(aw) > max_aw)?sign(aw)*max_aw:aw;
I think your are missing something. As far as i understand your code you always apply the max accelerations. If we get an acceleration below our limits as input the max acceleration is still used...

2017-02-15 16:28 UTC, ipa-bnm commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +    if (std::abs(sign(ax)*max_ax*period)<std::abs(vx_inc))
First you add the sign with `sign(ax)*max_ax` and after that you remove the sign with `std::abs` this is senseless.

2017-02-15 16:28 UTC, ipa-bnm commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +  boost::mutex::scoped_lock lock(_mutex);
I'm not sure if a mutex protection is needed. Timer and Callbacks are created from the same Nodehandle and the ros spinning model is single threaded. So only one callback at the time can be processed...

2017-02-15 16:28 UTC, ipa-bnm commented on cob_base_velocity_smoother/src/cob_base_velocity_smoother/velocity_smoother.cpp
> +
What happend with the odometry / robot feedback?

2018-03-03 14:32 UTC, closed without merging

2018-03-03 14:34 UTC, ipa-bnm commented
feel free to reopen this PR if you do not agree closing this.