Configurable base twist controller
4am-robotics/cob_control pull request #135
Opened 2017-02-14 11:32 UTC by ipa-fxm

#includes #134 

related to #91 
For the moment, we can only reconfigure the default values of the SteerCtrl parameters, i.e. the parameters are applied to all wheels...

@ipa-mdl 
Do you see any issue with this implementation regarding interference with the controller read-update-write cycle?

2017-02-14 11:41 UTC, mathias-luedtke requested changes
This cannot work properly as it is not thread-safe and not real-time-safe.

2017-02-14 11:49 UTC, ipa-mdl commented on cob_omni_drive_controller/src/control_plugin.cpp
> +    boost::recursive_mutex reconfig_mutex_;
recursive mutexes are evil.

2017-02-14 11:50 UTC, ipa-mdl commented on cob_omni_drive_controller/src/control_plugin.cpp
> +        geom_->reconfigureSteerCtrlParams(config);
not thread safe.

store data in realtime buffer and process in in `update()`.

2017-02-14 11:56 UTC, ipa-mdl commented
please merge bf7f138 separately.
I will provide a fix for cab763c

2017-02-14 17:39 UTC, ipa-fxm commented
Pull in @ipa-mdl's fixes + rebase as #134 has been merged

2017-02-14 19:31 UTC, ipa-mdl commented
I was not yet ready ;)
Per-joint option is missing, I will add (and squash) it tomorrow.

2017-02-15 10:39 UTC, ipa-fxm commented
@ipa-mdl 
Current implementation so far seems to work, i.e. rqt-reconfigured parameters are considered within the base_twist_controller, e.g. `d_phi_max`:
![reconfigure_dphimax](https://cloud.githubusercontent.com/assets/508006/22970705/54b7a2a2-f373-11e6-9490-b9269af1bac8.png)

2017-02-15 15:40 UTC, ipa-fxm commented
closing in favor of #137

2017-02-15 15:40 UTC, closed without merging