New singularity and joint limit avoidance method
4am-robotics/cob_control pull request #149
Opened 2017-03-16 13:39 UTC by ipa-bfb

2017-03-20 18:28 UTC, fmessmer requested changes
this PR is not cleanly separated from other features...please rebase to latest `ipa320/indigo_dev` but maybe hold until we merged #148

2017-03-20 18:30 UTC, ipa-fxm commented
also, you seem to use two different github user accounts...maybe you want to check your gitconfig files...

2017-03-22 17:09 UTC, ipa-fxm commented
@ipa-bfb now that #150 is merged, please rebase this PR

2017-03-23 10:06 UTC, ipa-bfb commented
Rebased... Let me know your comments...

2017-03-28 22:07 UTC, fmessmer requested changes
without looking into it too closely, I already found few things you already should know:
 - indentation!
 - do not change default values!
 - do not commit strange files (test/.idea/* files)
 - do not commit all the test files...they are to specific to merge to `ipa320/indigo_dev`...keep them on a test_branch of  yours...

2017-03-30 09:30 UTC, ipa-bfb commented
Well about the default values I think we could make this solver the default at the moment since is the one with the best stable behaviour despite it does not avoid self-collisions... What do you say?

2017-04-04 11:34 UTC, ipa-bfb commented
@ipa-fxm could you give me some feedback here?

2017-04-06 15:25 UTC, ipa-bfb commented on cob_twist_controller/scripts/test/test_careobot_st_jla_ca_sphere.py
> +        tracking_frame = rospy.get_param(action_name+'frame_tracker/target_frame')
if you run this node like `rosrun cob_twist_controller test_careobot_st_jla_ca_sphere.py __ns:=arm_left`, you do not need these changes...

2017-04-06 15:25 UTC, ipa-bfb commented on cob_twist_controller/src/cob_twist_controller.cpp
> +        ROS_ERROR("The Unified JLA and SA solution doesn\'t support collision avoidance. Currently UNIFIED_JLA_SA is only implemented for Identity and JLA ...");
adjust comment

2017-04-06 15:25 UTC, ipa-bfb commented on cob_twist_controller/src/constraint_solvers/constraint_solver_factory.cpp
> +        	 break;
fix indentation

2017-04-06 22:25 UTC, fmessmer approved these changes

2017-04-06 22:44 UTC, merged