Melodify/cob cobstacle distance
4am-robotics/cob_control pull request #203
Opened 2019-04-10 08:32 UTC by ipa-jba

api of kdl changed and now offers/requires a) updateInternalDataStructures and b) an extended version of JntToCart to be implemented. With the new melodic api (Version 1.4.0) in theory the Advanced..recursive solvers get obsolete, but to keep backward compatiblity I copied the newly added functions. They are unused however

2019-04-11 19:32 UTC, fmessmer requested changes
please rebase to enable melodic tests in travis

2019-04-12 12:22 UTC, benmaidel submitted a review, later dismissed

2019-04-12 12:22 UTC, benmaidel commented on cob_obstacle_distance/src/debug/debug_obstacle_distance_node.cpp
> -            marker_distance.text = boost::lexical_cast<std::string>(boost::format("%.3f") % it->second.distance);
alternative solution:
```
#include <boost/format.hpp>
```

2019-06-03 15:42 UTC, ipa-jba commented
close in favour of #208

2019-06-03 15:42 UTC, closed without merging