add initialpose to emulation_base
4am-robotics/cob_control pull request #216
Opened 2019-10-08 17:09 UTC by benmaidel

2019-10-09 07:58 UTC, floweisshardt requested changes
2D pose estimate is not working properly. It currently just sets the transformation from map to odom_combined and does not take base_link to odom_combined into account. The result is that the robot is not localized at the pose which is specified by 2D pose estimate

2019-10-09 07:58 UTC, floweisshardt commented on cob_hardware_emulation/scripts/emulation_base.py
> +from tf_conversions import
syntax error

2019-10-09 07:58 UTC, floweisshardt commented on cob_hardware_emulation/scripts/emulation_base.py
>          # - add service reset odometry
add service reset odometry (/base/odometry_controller/reset_odometry [std_srvs::Trigger])

2019-10-09 07:58 UTC, floweisshardt commented on cob_hardware_emulation/scripts/emulation_base.py
> +        t_odom.transform. = self.initial_pose
syntax error

2019-10-09 07:58 UTC, floweisshardt commented on cob_hardware_emulation/scripts/emulation_base.py
> +        rospy.Subscriber("/initalpose", PoseWithCovarianceStamped, self.initalpose_callback, queue_size=1)
typo: inital --> init**i**al

2019-10-09 18:30 UTC, benmaidel commented
> 2D pose estimate is not working properly. It currently just sets the transformation from map to odom_combined and does not take base_link to odom_combined into account. The result is that the robot is not localized at the pose which is specified by 2D pose estimate

simple fix for now, by resetting odometry on initalpose

2019-10-15 10:38 UTC, floweisshardt approved these changes

2019-10-15 10:38 UTC, floweisshardt commented
workaround with resetting odometry works for now. Remaining issue is tracked in https://github.com/mojin-robotics/cob4/issues/1281

2019-10-15 10:39 UTC, merged