[WIP] Add recover from diagnostic errors
4am-robotics/cob_control pull request #272
Opened 2022-12-01 20:01 UTC by Deleh

Adds recovery from diagnostic errors to `halt_detector`.

2022-12-01 22:05 UTC, fmessmer reviewed
not sure this is generic enough - although `halt_detector` is currently only used for kevins
maybe it needs more configurability so that the diagnostics recovery and/or which error codes to react to can be configured specifically to the robot

2022-12-02 08:46 UTC, Deleh commented
> not sure this is generic enough - although `halt_detector` is currently only used for kevins
> maybe it needs more configurability so that the diagnostics recovery and/or which error codes to react to can be configured specifically to the robot

This should be given by setting the _diagnostic recovery trigger_ parameter per robot. The launch file needs to be adjusted to not overwrite it

2022-12-05 15:00 UTC, floweisshardt requested changes

2022-12-05 15:00 UTC, floweisshardt commented on cob_base_controller_utils/launch/halt_detector.launch
> +    <rosparam param="halt_detector/diagnostic_recovery_trigger">['ff20#0']</rosparam>
make this an entry (list of strings) in a robot specific yaml file in mojin_hardware_config

2022-12-06 07:40 UTC, floweisshardt requested changes

2022-12-06 07:40 UTC, floweisshardt commented on cob_base_controller_utils/config/halt_detector.yaml
> +diagnostic_recovery_trigger: []
this yaml file lives in mojin_hardware_config. remove here

2022-12-06 07:40 UTC, floweisshardt commented on cob_base_controller_utils/launch/halt_detector.launch
> +  <arg name="config_file" default="$(find cob_base_controller_utils)/config/halt_detector.yaml" />
remove default

2022-12-06 07:40 UTC, floweisshardt commented on cob_base_controller_utils/launch/halt_detector.launch
> +    <rosparam command="load" ns="halt_detector" file="$(arg config_file)" />
move rosparam inside node tag

2022-12-06 07:54 UTC, floweisshardt approved these changes

2022-12-06 09:33 UTC, merged